### ISSUE TITLE
Module is creating a classical load balancer.

### ISSUE THREAD

**Issue by pessoa** [montblu/terraform-kubernetes-jumpserver#6]
Ideally it should add to an existing NLB or create its own.

**Comment by jdaMachado** [comment]
With the new change, it's able to create its own NLB. However, to avoid repeating annotations between clients, we should be able to use flags to set default annotations cloud provider-specific. We could add these individual annotations as map variables and use them with bool attributes on module declaration.

**Comment by jdaMachado** [comment]
This is still open because we haven't figured out how to reuse an existing LB.

**Comment by pessoa** [comment]
svc_create = false from https://github.com/montblu/terraform-kubernetes-jumpserver/issues/17 to reuse the same NLB.
